# Generated by Django 2.0.6 on 2018-11-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('book_cat', models.CharField(max_length=30)),
                ('book_auth', models.CharField(max_length=30)),
                ('book_pub', models.CharField(max_length=30)),
                ('book_price', models.FloatField()),
                ('book_qty', models.IntegerField()),
            ],
        ),
    ]
