# Generated by Django 2.0.6 on 2018-11-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0002_auto_20181111_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='shelf_no',
            field=models.IntegerField(default=5),
        ),
    ]
